package com.xiaobaidu.ecoupon.entity;

import java.util.Date;

public class ECouponType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon_type.ID
     *
     * @mbg.generated Sun Jun 04 02:57:09 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon_type.TYPE_CODE
     *
     * @mbg.generated Sun Jun 04 02:57:09 CST 2017
     */
    private String typeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon_type.TYPE_NAME
     *
     * @mbg.generated Sun Jun 04 02:57:09 CST 2017
     */
    private String typeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon_type.REMARK
     *
     * @mbg.generated Sun Jun 04 02:57:09 CST 2017
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon_type.CREATOR
     *
     * @mbg.generated Sun Jun 04 02:57:09 CST 2017
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon_type.CREATE_TIME
     *
     * @mbg.generated Sun Jun 04 02:57:09 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon_type.EDITOR
     *
     * @mbg.generated Sun Jun 04 02:57:09 CST 2017
     */
    private String editor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon_type.EDIT_TIME
     *
     * @mbg.generated Sun Jun 04 02:57:09 CST 2017
     */
    private Date editTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon_type.ID
     *
     * @return the value of e_coupon_type.ID
     *
     * @mbg.generated Sun Jun 04 02:57:09 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon_type.ID
     *
     * @param id the value for e_coupon_type.ID
     *
     * @mbg.generated Sun Jun 04 02:57:09 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon_type.TYPE_CODE
     *
     * @return the value of e_coupon_type.TYPE_CODE
     *
     * @mbg.generated Sun Jun 04 02:57:09 CST 2017
     */
    public String getTypeCode() {
        return typeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon_type.TYPE_CODE
     *
     * @param typeCode the value for e_coupon_type.TYPE_CODE
     *
     * @mbg.generated Sun Jun 04 02:57:09 CST 2017
     */
    public void setTypeCode(String typeCode) {
        this.typeCode = typeCode == null ? null : typeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon_type.TYPE_NAME
     *
     * @return the value of e_coupon_type.TYPE_NAME
     *
     * @mbg.generated Sun Jun 04 02:57:09 CST 2017
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon_type.TYPE_NAME
     *
     * @param typeName the value for e_coupon_type.TYPE_NAME
     *
     * @mbg.generated Sun Jun 04 02:57:09 CST 2017
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon_type.REMARK
     *
     * @return the value of e_coupon_type.REMARK
     *
     * @mbg.generated Sun Jun 04 02:57:09 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon_type.REMARK
     *
     * @param remark the value for e_coupon_type.REMARK
     *
     * @mbg.generated Sun Jun 04 02:57:09 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon_type.CREATOR
     *
     * @return the value of e_coupon_type.CREATOR
     *
     * @mbg.generated Sun Jun 04 02:57:09 CST 2017
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon_type.CREATOR
     *
     * @param creator the value for e_coupon_type.CREATOR
     *
     * @mbg.generated Sun Jun 04 02:57:09 CST 2017
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon_type.CREATE_TIME
     *
     * @return the value of e_coupon_type.CREATE_TIME
     *
     * @mbg.generated Sun Jun 04 02:57:09 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon_type.CREATE_TIME
     *
     * @param createTime the value for e_coupon_type.CREATE_TIME
     *
     * @mbg.generated Sun Jun 04 02:57:09 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon_type.EDITOR
     *
     * @return the value of e_coupon_type.EDITOR
     *
     * @mbg.generated Sun Jun 04 02:57:09 CST 2017
     */
    public String getEditor() {
        return editor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon_type.EDITOR
     *
     * @param editor the value for e_coupon_type.EDITOR
     *
     * @mbg.generated Sun Jun 04 02:57:09 CST 2017
     */
    public void setEditor(String editor) {
        this.editor = editor == null ? null : editor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon_type.EDIT_TIME
     *
     * @return the value of e_coupon_type.EDIT_TIME
     *
     * @mbg.generated Sun Jun 04 02:57:09 CST 2017
     */
    public Date getEditTime() {
        return editTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon_type.EDIT_TIME
     *
     * @param editTime the value for e_coupon_type.EDIT_TIME
     *
     * @mbg.generated Sun Jun 04 02:57:09 CST 2017
     */
    public void setEditTime(Date editTime) {
        this.editTime = editTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_coupon_type
     *
     * @mbg.generated Sun Jun 04 02:57:09 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", typeCode=").append(typeCode);
        sb.append(", typeName=").append(typeName);
        sb.append(", remark=").append(remark);
        sb.append(", creator=").append(creator);
        sb.append(", createTime=").append(createTime);
        sb.append(", editor=").append(editor);
        sb.append(", editTime=").append(editTime);
        sb.append("]");
        return sb.toString();
    }
}