package com.xiaobaidu.ecoupon.dao;

import com.xiaobaidu.ecoupon.entity.ECouponType;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;
@Mapper
public interface ECouponTypeMapper extends IQuery {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_coupon_type
     *
     * @mbg.generated Sun Jun 04 02:57:09 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_coupon_type
     *
     * @mbg.generated Sun Jun 04 02:57:09 CST 2017
     */
    int insert(ECouponType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_coupon_type
     *
     * @mbg.generated Sun Jun 04 02:57:09 CST 2017
     */
    ECouponType selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_coupon_type
     *
     * @mbg.generated Sun Jun 04 02:57:09 CST 2017
     */
    List<ECouponType> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_coupon_type
     *
     * @mbg.generated Sun Jun 04 02:57:09 CST 2017
     */
    int updateByPrimaryKey(ECouponType record);
}