package com.xiaobaidu.ecoupon.dao;

import org.apache.ibatis.session.RowBounds;

import java.util.List;


/**
 * 查詢接口
 * 
 * @param <T>
 *            实体类对象
 */
public interface IQuery<T> {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table AccountDemo
	 *
	 * @mbg.generated Mon Mar 20 21:12:40 CST 2017
	 */
	int deleteByPrimaryKey(String accountd_Id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table AccountDemo
	 *
	 * @mbg.generated Mon Mar 20 21:12:40 CST 2017
	 */
	int insert(T record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table AccountDemo
	 *
	 * @mbg.generated Mon Mar 20 21:12:40 CST 2017
	 */
	T selectByPrimaryKey(String accountId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table AccountDemo
	 *
	 * @mbg.generated Mon Mar 20 21:12:40 CST 2017
	 */
	List<T> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table AccountDemo
	 *
	 * @mbg.generated Mon Mar 20 21:12:40 CST 2017
	 */
	int updateByPrimaryKey(T record);

	long countByExample(Object example);

	List<T> selectByExampleWithRowbounds(Object example, RowBounds rowBounds);
}
